# Generated by Django 5.1.5 on 2026-03-30 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CEDULA CIUDADANIA', 'Cc'), ('TARJETA IDENTIDAD', 'Ti'), ('REGISTRO CIVIL', 'Rc'), ('CEDULA EXTRANJERIA', 'Ce'), ('PASAPORTE', 'Pa')], max_length=25)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, default='', max_length=50)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('MASCULINO', 'M'), ('FEMENINO', 'F')], max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comuneros', to='territories.territory')),
            ],
            options={
                'db_table': 'comuneros',
                'ordering': ['first_last_name', 'first_name'],
            },
        ),
    ]
